const EVENTS = {
	IS_NIGHT: 'isNight',
	SUNRISE: 'sunrise',
	SUNSET: 'sunset'
};

const A_MILLISECOND = 1,
			A_SECOND = 1000*A_MILLISECOND,
			A_MINUTE = 60*A_SECOND,
			AN_HOUR = 60*A_MINUTE,
			A_DAY = 24*AN_HOUR;

const TIME = {
	A_MILLISECOND: A_MILLISECOND,
  A_SECOND: A_SECOND,
  A_MINUTE: A_MINUTE,
  AN_HOUR: AN_HOUR,
  A_DAY: A_DAY
};
